Fix compilation for non-lite version
bincrafters/conan-center-index pull request #17
Opened 2020-11-03 19:59 UTC by Hopobcn

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Please consider these changes.
I've tried with v3.9.1, v3.11.4, v3.12.4 with default options and seems to work in my machine (macos)

2020-11-04 17:17 UTC, uilianries requested changes

2020-11-04 17:17 UTC, uilianries commented on recipes/protobuf/all/conanfile.py
> +                    tools.patch(**patch)
```suggestion
        for patch in self.conan_data.get("patches", {}).get(self.version, []):
            tools.patch(**patch)
```

2020-11-04 17:17 UTC, uilianries commented on recipes/protobuf/all/test_package/conanfile.py
> +        #cmake.definitions["protobuf_LITE"] = self.options["protobuf"].lite
```suggestion
```

Remove if not used

2020-11-05 17:49 UTC, uilianries commented
@Hopobcn Great job, could you please solve the conflict.

2020-11-05 18:57 UTC, Hopobcn commented
I've resolved the conflicts. Since now bincrafters:protobuf/3.12.3 builds, my MR has been reduced to only cosmetic changes. Feel free to cherry-pick or not.

2020-11-06 12:22 UTC, uilianries approved these changes

2020-11-06 12:22 UTC, merged

2020-11-06 12:22 UTC, uilianries commented
@Hopobcn Thanks, Your test package looks better!